Lab5
user27763397/lab5 pull request #1
Opened 2023-11-29 16:03 UTC by user27763397

2023-11-30 12:07 UTC, Vitaliiir16 approved these changes
i like this code, i didnt find troubles

2024-01-01 14:25 UTC, zveres-ss requested changes

2024-01-01 14:25 UTC, zveres-ss commented on README.md
> +Виведення інформації (display_info): Виводить ім'я кандидата та кількість голосів, які він отримав.
лишня інформація, вона має бутина рівні коментаря до класу, а не в readme.md файлі

2024-01-01 14:25 UTC, zveres-ss commented on README.md
> +
лишня інформація, вона має бутина рівні коментаря до класу, а не в readme.md файлі

2024-01-01 14:25 UTC, zveres-ss commented on lab5.py
> +    # Метод для встановлення кількості голосів кандидата
please convert this commends in docstring ones

2024-01-06 15:27 UTC, merged

2024-01-06 15:31 UTC, user27763397 commented
Я не туди жмав

https://github.com/user27763397/lab5/pull/2/commits/07e5014f3cb3b3f7b7a7076ab705f4623261fde2